import { motion } from 'framer-motion';
import { BookOpenCheck, CheckCircle2, Sparkles, Target } from 'lucide-react';

export default function AuthLayout({ children, title, subtitle }) {
  return <div className="relative grid min-h-screen overflow-hidden bg-[#f5f7ff] dark:bg-[#0d1020] lg:grid-cols-[1.05fr_.95fr]">
    <div className="absolute -left-32 -top-32 h-96 w-96 rounded-full bg-primary-400/20 blur-3xl"/><div className="absolute -bottom-40 right-0 h-[30rem] w-[30rem] rounded-full bg-violet-500/20 blur-3xl"/>
    <section className="relative hidden overflow-hidden bg-gradient-to-br from-[#4555d7] via-[#6d55df] to-[#8a52dc] p-14 text-white lg:flex lg:flex-col"><div className="absolute inset-0 opacity-10" style={{backgroundImage:'radial-gradient(circle at 2px 2px, white 1px, transparent 0)',backgroundSize:'26px 26px'}}/><div className="relative flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15 backdrop-blur"><Target /></div><div><p className="text-xl font-extrabold">Focus90</p><p className="text-xs text-white/60">Bank Exam Sprint</p></div></div><div className="relative my-auto max-w-xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-semibold backdrop-blur"><Sparkles size={15}/> Built for focused aspirants</div><h1 className="text-5xl font-extrabold leading-[1.12] tracking-tight">Small efforts.<br/>Remarkable results.</h1><p className="mt-6 max-w-md text-base leading-7 text-white/70">Build the consistency that turns preparation into confidence, one intentional study day at a time.</p><div className="mt-10 grid max-w-md grid-cols-2 gap-4">{[['90','Focused days'],['1','Clear goal']].map(([n,l])=><div key={l} className="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur"><p className="text-3xl font-bold">{n}</p><p className="text-xs text-white/60">{l}</p></div>)}</div></div><p className="relative text-xs text-white/50">“Discipline is choosing between what you want now and what you want most.”</p></section>
    <section className="relative grid place-items-center px-5 py-10"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="w-full max-w-[460px]"><div className="mb-8 flex items-center gap-3 lg:hidden"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary-500 text-white"><BookOpenCheck size={22}/></div><p className="text-xl font-extrabold">Focus90</p></div><div className="mb-8"><div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-primary-50 text-primary-500 dark:bg-primary-500/10"><CheckCircle2/></div><h2 className="text-3xl font-extrabold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p></div>{children}</motion.div></section>
  </div>;
}
